### ISSUE TITLE
Compatibility warning for Piwik 3.0.3.

### ISSUE THREAD

**Issue by Chris6284** [piwik/plugin-MarketingCampaignsReporting#10]
Hi Piwik team,

afte the update to Piwik 3.0.3 we got a message that this plugin is not ready for this Piwik-Version.
Any tips for this problem?

Greetings

**Comment by sgiehl** [comment]
This is weird. The plugin is defined as compatible with any Piwik 3 version. Could you check the piwik requirement in the plugin.json of the plugin?

**Comment by Chris6284** [comment]
Thanks for the quick response.

It was my fault. I did not copy your plugin in the new folder by upgrading from Piwik 3.0.2 to 3.0.3.
The error-message from Piwik is missleading. Should be something like "Could not find the plugin xxx. Check if folder xxx exists."

**Comment by sgiehl** [comment]
Ok. Thanks for the feedback. I'll have a look and try to improve the message in Piwik.
Cheers
