### ISSUE TITLE
Piwik 3.0.4 Problem after installation saying "Unknown column 'campaign_content' in 'field list'"

### ISSUE THREAD

**Issue by komtur** [piwik/plugin-MarketingCampaignsReporting#13]
The apache error log is saying:
`[Thu Aug 03 09:15:48.424756 2017] [proxy_fcgi:error] [pid 35602:tid 139702267016960] [client xx.xx.xx.xx:57993] AH01071: Got error 'PHP message: Error in Piwik (tracker): Error query: fetch() failed: Unknown column 'campaign_content' in 'field list' : SELECT visit_last_action_time, visit_first_action_time, idvisitor, idvisit, user_id, visit_exit_idaction_url, visit_exit_idaction_name, visitor_returning, visitor_days_since_first, visitor_days_since_order, visitor_count_visits, visit_goal_buyer, location_country, location_region, location_city, location_latitude, location_longitude, referer_name, referer_keyword, referer_type, idsite, visit_entry_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, config_device_brand, config_device_model, config_device_type, visit_total_events, visit_total_time, location_ip, location_browser_lang, campaign_content, campaign_id, campaign_keyword, campaign_medium, campaign_name, campaign_source, custom_var_k1, custom_var_v1, custom_var_k2, custom_var_v2, custom_var_k3, custom_var_v3, custom_var_k4, custom_var_v4, custom_var_k5, custom_var_v5   FROM piwik_log_visit WHERE visi...\n'
[Thu Aug 03 09:15:48.485012 2017] [proxy_fcgi:error] [pid 35694:tid 139702124340992] [client xx.xx.xx.xx:26114] AH01071: Got error 'PHP message: Error in Piwik (tracker): Error query: fetch() failed: Unknown column 'campaign_content' in 'field list' : SELECT visit_last_action_time, visit_first_action_time, idvisitor, idvisit, user_id, visit_exit_idaction_url, visit_exit_idaction_name, visitor_returning, visitor_days_since_first, visitor_days_since_order, visitor_count_visits, visit_goal_buyer, location_country, location_region, location_city, location_latitude, location_longitude, referer_name, referer_keyword, referer_type, idsite, visit_entry_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, config_device_brand, config_device_model, config_device_type, visit_total_events, visit_total_time, location_ip, location_browser_lang, campaign_content, campaign_id, campaign_keyword, campaign_medium, campaign_name, campaign_source, custom_var_k1, custom_var_v1, custom_var_k2, custom_var_v2, custom_var_k3, custom_var_v3, custom_var_k4, custom_var_v4, custom_var_k5, custom_var_v5   FROM piwik_log_visit WHERE visi...\n'`

**Comment by KZeni** [comment]
I was getting errors in the Piwik web interface with `MarketingCampaignsReporting.php(107): Notice - Undefined index: campaign_id` & plenty of other similar errors being reported.

**Comment by mattab** [comment]
Hi there, thanks for the report. This issue should not occur and we're not sure how this could happen. But in order to provide a workaround, could you try the following:
* Remove the two lines containing `MarketingCampaignsReporting` in your config.ini.php
* Delete the folder `plugins/MarketingCampaignsReporting`
* Then go to Piwik > Admin > Marketplace, and re-install the plugin
* You may need to run the `./console core:update` in the command line for the upgrade to succeed without timeout in the browser

Could you try this and let us know if this fixes the issue?

**Comment by KZeni** [comment]
I uninstalled the plugin via the Plugin page, re-installed the plugin, activated it, and used the ./console core:update command instead of performing the database update via my browser. The DB update worked successfully and I clicked to finish the update and saw the plugin was activated successfully!

So, from what I can tell, it appears that uninstalling & re-installing addressed the partial installation from before and using the CLI command instead of the web browser to update the database prevented the partial DB update which caused the issue last time.

Thanks!

**Comment by mattab** [comment]
Thanks for confirming. We sometimes have this issue when installing a plugin triggers a big database schema change which takes too long to run in the browser. Left a comment in our Upgrader issue here: https://github.com/piwik/piwik/issues/5985#issuecomment-330355443

**Comment by komtur** [comment]
Thanx to @KZeni !

The `./console core:update` trick does it quite well, but my error in the apache error log remained.
The table columns where still missing. I have to mention, I run a bigger piwik installation (piwik_log_visit table is > 75 GB).

So what does the trick then?

Uninstalling the PlugIn via the Plugin page

Re-installed the PlugIn via the Plugin page & activate it

Run the `./console core:update` command
Check the structure of the piwik tables piwik_log_visit and piwik_log_conversion.
If there is no column 'campaign_id' run the SQL Statements manually directly in mysql:
`ALTER TABLE `piwik_log_visit` ADD COLUMN `campaign_content` VARCHAR(255) NULL, ADD COLUMN `campaign_id` VARCHAR(100) NULL, ADD COLUMN `campaign_keyword` VARCHAR(255) NULL, ADD COLUMN `campaign_medium` VARCHAR(255) NULL, ADD COLUMN `campaign_name` VARCHAR(255) NULL, ADD COLUMN `campaign_source` VARCHAR(255) NULL;`
and 
ALTER TABLE `piwik_log_conversion` ADD COLUMN `campaign_content` VARCHAR(255) NULL, ADD COLUMN `campaign_id` VARCHAR(100) NULL, ADD COLUMN `campaign_keyword` VARCHAR(255) NULL, ADD COLUMN `campaign_medium` VARCHAR(255) NULL, ADD COLUMN `campaign_name` VARCHAR(255) NULL, ADD COLUMN `campaign_source` VARCHAR(255) NULL;
manually
You might get errors saying:
> ERROR 1296 (HY000): Got error 64 'Temp file write failure' from InnoDB. This means the table is too large to be altered directly.
The `./console core:update` doesn't show this cancellation of mysql.

This worked for me:
0) Backup the DB!

1) Copy the MYSQL Structure:
`CREATE TABLE `piwik_log_visit_new` LIKE `piwik_log_visit`;`
`CREATE TABLE `piwik_log_conversion_new` LIKE `piwik_log_conversion`;`

2) Run the Update Command on the (empty) new tables:
`ALTER TABLE `piwik_log_visit_new` ADD COLUMN `campaign_content` VARCHAR(255) NULL, ADD COLUMN `campaign_id` VARCHAR(100) NULL, ADD COLUMN `campaign_keyword` VARCHAR(255) NULL, ADD COLUMN `campaign_medium` VARCHAR(255) NULL, ADD COLUMN `campaign_name` VARCHAR(255) NULL, ADD COLUMN `campaign_source` VARCHAR(255) NULL;`
ALTER TABLE `piwik_log_conversion_new` ADD COLUMN `campaign_content` VARCHAR(255) NULL, ADD COLUMN `campaign_id` VARCHAR(100) NULL, ADD COLUMN `campaign_keyword` VARCHAR(255) NULL, ADD COLUMN `campaign_medium` VARCHAR(255) NULL, ADD COLUMN `campaign_name` VARCHAR(255) NULL, ADD COLUMN `campaign_source` VARCHAR(255) NULL;

3) Now copy the contents of the tables to the new (modified) tables:
`insert into piwik_log_visit_new(idvisit,idsite,idvisitor,visitor_localtime,visitor_returning,visitor_count_visits,visitor_days_since_last,visitor_days_since_order,visitor_days_since_first,visit_first_action_time,visit_last_action_time,visit_exit_idaction_url,visit_exit_idaction_name,visit_entry_idaction_url,visit_entry_idaction_name,visit_total_actions,visit_total_searches,visit_total_events,visit_total_time,visit_goal_converted,visit_goal_buyer,referer_type,referer_name,referer_url,referer_keyword,config_id,config_os,config_os_version,config_browser_name,config_browser_version,config_device_type,config_device_brand,config_device_model,config_resolution,config_pdf,config_flash,config_java,config_director,config_quicktime,config_realplayer,config_windowsmedia,config_gears,config_silverlight,config_cookie,location_ip,location_browser_lang,location_country,location_region,location_city,location_latitude,location_longitude,custom_var_k1,custom_var_v1,custom_var_k2,custom_var_v2,custom_var_k3,custom_var_v3,custom_var_k4,custom_var_v4,custom_var_k5,custom_var_v5,location_provider,user_id,config_browser_engine,visit_total_interactions) SELECT * FROM piwik_log_visit;`
`insert into piwik_log_conversion_new(idvisit,idsite,idvisitor,server_time,idaction_url,idlink_va,referer_visit_server_date,referer_type,referer_name,referer_keyword,visitor_returning,visitor_count_visits,visitor_days_since_first,visitor_days_since_order,location_country,location_region,location_city,location_latitude, location_longitude,url,idgoal,buster,idorder,items,revenue,revenue_subtotal,revenue_tax,revenue_shipping,revenue_discount,custom_var_k1,custom_var_v1,custom_var_k2,custom_var_v2,custom_var_k3,custom_var_v3,custom_var_k4,custom_var_v4,custom_var_k5,custom_var_v5,config_device_brand,config_device_model,config_device_type) SELECT * FROM piwik_log_conversion;`

4)
Now swap the table names:
RENAME TABLE  `piwik_log_conversion` TO  `piwik_log_conversion_old`
RENAME TABLE  `piwik_log_conversion_new` TO  `piwik_log_conversion`
RENAME TABLE  `piwik_log_visit` TO  `piwik_log_visit_old`
RENAME TABLE  `piwik_log_visit_new` TO  `piwik_log_visit`

**Comment by komtur** [comment]
Confirmed. Didn't see any error in the core console. Console said I was completing without any errors.
