### ISSUE TITLE
Make our URL builder support tagging URLs with Source and Medium and Content tags

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-MarketingCampaignsReporting#2]
Our URL builder https://piwik.org/docs/tracking-campaigns-url-builder/ should support tagging URL with 
* Campaign source (optional) Used to track the source of the campaign such as "newsletter" for your email marketing, "affiliate", or the name of the website displaying your ads ->  `pk_source`
* Campaign medium (optional) Used to describe the marketing activity, for example "PPC" for a pay-per-click campaign, or "SEM" for a paid search ads, or "review" to track a product review on an affiliate site `pk_medium`
* Campaign content (optional) This parameter is often used when you are testing multiple ads, and would include the name of each ad to see which was most effective for driving traffic. `pk_content`

**Comment by tsteur** [comment]
Done
