### ISSUE TITLE
Error message in nginx log - "array_key_exists() in Base.php"

### ISSUE THREAD

**Issue by makarovstas** [piwik/plugin-MarketingCampaignsReporting#7]
Hi Piwik Team!
I'm tested plug-in and found small bug in nginx error log:
2017/03/17 01:00:47 [error] 7122#7122: *18004 FastCGI sent in stderr: "PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /plugins/MarketingCampaignsReporting/Columns/Base.php on line 101
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /plugins/MarketingCampaignsReporting/Columns/Base.php on line 101

This error only occurs when I visit website without any "utm_ "  or "_pk" parameters. 
If I visit site with "?utm_source=test", this warning does not appear

**Comment by sgiehl** [comment]
Thanks or the report. Will fix that soon

**Comment by sgiehl** [comment]
is fixed in new release 3.0.2
